// Auto-generated from public/store.html (Phase C extraction)
// This is a small curated seed dataset used as a fallback + UI hints.
window.__AITOPIA_STORE_FEATURED_AGENTS__ = {
  'virtual-try-on': {
    id: 'virtual-try-on',
    name: 'Virtual Try-On',
    category: 'E-Commerce',
    categoryKey: 'ecommerce',
    description: 'Transform outfits on any person by uploading a full-body photo and a clothing reference image. The AI precisely replaces attire while preserving facial features, hairstyle, pose, and background. Perfect for e-commerce sellers to visualize products on different models.',
    icon: 'https://aitopia.ai/agent-images/virtual-try-on-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/virtual-try-on-1.webp'],
    rating: 4.8,
    reviews: '15.2K',
    price: '$0.50',
    features: ['Person validation', 'Garment classification', 'Virtual fitting', 'Multiple garment types', 'Model selection', 'Gender & body filters'],
    developer: 'MuleRun',
    popular: true,
    // Fashion model gallery configuration
    garmentTypes: ['tops', 'bottoms', 'dresses', 'outerwear', 'full-body'],
    // Fashion model photos for the gallery (female models in neutral poses)
    modelGallery: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=300&fit=crop',
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=200&h=300&fit=crop',
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=200&h=300&fit=crop',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&h=300&fit=crop',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&h=300&fit=crop',
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&h=300&fit=crop',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=300&fit=crop',
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=300&fit=crop'
    ],
    genderOptions: ['All Genders', 'Female', 'Male'],
    bodyTypes: ['All body types', 'Slim', 'Athletic', 'Plus size'],
    // Sample outfit images for reference
    outfitSamples: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=150&h=200&fit=crop',
      'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=150&h=200&fit=crop',
      'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=150&h=200&fit=crop'
    ]
  },
  'face-swap': {
    id: 'face-swap',
    name: 'Face Swap',
    category: 'Image Editing',
    categoryKey: 'image',
    description: 'Swap faces between photos in seconds. Upload a source face and target photo—AI detects, aligns, and blends naturally. Biometric consent checks included.',
    icon: 'https://aitopia.ai/agent-images/face-swap-1.webp',
    screenshots: [
      'https://aitopia.ai/agent-images/face-swap-1.webp'
    ],
    rating: 4.7,
    reviews: '12.8K',
    price: 'Credits-based',
    features: ['High quality swap', 'Face detection', 'Natural blending', 'Consent checks'],
    developer: 'Higgsfield AI',
    popular: true,
    // Face swap specific options
    swapModes: ['Single face', 'All faces', 'Select faces'],
    enhancementOptions: ['Skin smoothing', 'Color correction', 'Edge blending']
  },
  'image-generator': {
    id: 'image-generator',
    name: 'Image Generator',
    category: 'AI Art',
    categoryKey: 'image',
    description: 'Multi-provider AI image generation using DALL-E 3, Stability AI, and Flux models.',
    icon: 'https://aitopia.ai/agent-images/image-generator-1.webp',
    screenshots: [
      'https://aitopia.ai/agent-images/image-generator-1.webp'
    ],
    rating: 4.9,
    reviews: '28.5K',
    price: '$0.30',
    features: ['DALL-E 3', 'Stability SDXL', 'Flux Models', 'Multiple Styles'],
    developer: 'Higgsfield AI',
    popular: true,
    // Image generation specific options
    models: [
      { name: 'DALL-E 3', icon: '🎨' },
      { name: 'Stability SDXL', icon: '🖼️' },
      { name: 'Flux Pro', icon: '✨' },
      { name: 'Midjourney Style', icon: '🌟' },
      // Google Imagen models (December 2025)
      { name: 'Google Imagen 4 Ultra', icon: '🔷' },
      { name: 'Google Imagen 4', icon: '🔷' },
      { name: 'Google Imagen 4 Fast', icon: '🔷' },
      { name: 'Google Imagen 3', icon: '🔷' },
      { name: 'Google Imagen 3 Fast', icon: '🔷' },
      { name: 'Google Gemini Flash Image', icon: '🔷' },
      // NVIDIA SANA models (December 2025)
      { name: 'NVIDIA SANA Sprint', icon: '🟢' },
      { name: 'NVIDIA SANA', icon: '🟢' },
    ],
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    styles: ['Photorealistic', 'Anime', 'Digital Art', 'Oil Painting', 'Watercolor', 'Sketch', '3D Render', 'Cinematic'],
    promptSuggestions: [
      'A serene mountain landscape at sunset',
      'Futuristic city with flying cars',
      'Portrait of a warrior in golden armor',
      'Enchanted forest with magical creatures'
    ]
  },
  'background-remover': {
    id: 'background-remover',
    name: 'Background Remover',
    category: 'Image',
    categoryKey: 'image',
    description: 'Remove backgrounds from images instantly using AI with high quality edges.',
    icon: 'https://aitopia.ai/agent-images/background-remover-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/background-remover-1.webp'],
    rating: 4.8,
    reviews: '45.1K',
    price: 'Free',
    features: ['Instant removal', 'High quality edges', 'Transparent PNG', 'Batch processing'],
    developer: 'MuleRun',
    popular: true
  },
  'video-generator': {
    id: 'video-generator',
    name: 'Video Generator',
    category: 'Video',
    categoryKey: 'video',
    description: 'Make videos in one click with 250+ presets for camera control, framing, and high-quality VFX. Upload a start frame, choose a preset to control your image movement, then generate your final animated video with industry-leading models.',
    icon: 'https://aitopia.ai/agent-images/video-generator-1.webp',
    screenshots: ["https://aitopia.ai/agent-images/video-generator-1.webp"],
    rating: 4.9,
    reviews: '8.3K',
    price: '$2.00',
    features: ['Text-to-Video', 'Image-to-Video', '250+ Presets', 'Camera Control', 'VFX Effects', '4K Output'],
    developer: 'Higgsfield AI',
    popular: true,
    // Video generation models - id must match backend model identifiers
    // Models with 🎯 support end frame transitions
    models: [
      { id: 'kling-pro', name: 'Kling Pro 🎯', icon: '🎥', supportsEndFrame: true },
      { id: 'minimax-hailuo', name: 'Minimax Hailuo 🎯', icon: '✨', supportsEndFrame: true },
      { id: 'luma-ray', name: 'Luma Ray 🎯', icon: '🌟', supportsEndFrame: true },
      { id: 'kling-2.5-turbo', name: 'Kling 2.5 Turbo', icon: '⚡', supportsEndFrame: false },
      { id: 'wan-2.1', name: 'Wan 2.1', icon: '🌊', supportsEndFrame: false },
      // Google Veo models (December 2025)
      { id: 'veo-3.1', name: 'Google Veo 3.1', icon: '🔷', supportsEndFrame: false },
      { id: 'veo-3.1-fast', name: 'Google Veo 3.1 Fast', icon: '🔷', supportsEndFrame: false },
      { id: 'veo-3', name: 'Google Veo 3', icon: '🔷', supportsEndFrame: false },
      { id: 'veo-3-fast', name: 'Google Veo 3 Fast', icon: '🔷', supportsEndFrame: false },
      { id: 'veo-2', name: 'Google Veo 2', icon: '🔷', supportsEndFrame: false },
    ],
    durations: ['5s', '10s', '15s', '30s'],
    resolutions: ['720p', '1080p', '4K'],
    presetCategories: ['General', 'Cinematic', 'Action', 'Slow Motion', 'Zoom', 'Pan', 'Tracking']
  },
  'image-upscaler': {
    id: 'image-upscaler',
    name: 'Image Upscaler',
    category: 'Image',
    categoryKey: 'image',
    description: 'Enhance resolution and quality using the Topaz upscaler. Upscale images up to 4x while preserving details, reducing noise, and enhancing faces automatically.',
    icon: 'https://aitopia.ai/agent-images/upscaler-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/upscaler-1.webp'],
    rating: 4.8,
    reviews: '22.4K',
    price: '$0.20',
    features: ['4x Upscale', 'Noise Reduction', 'Face Enhancement', 'Detail Restoration', 'Topaz Quality'],
    developer: 'MuleRun',
    popular: true,
    // Upscaler specific options
    scaleOptions: ['2x', '4x', '8x'],
    enhancementTypes: ['General', 'Photo', 'Anime', 'Art'],
    noiseReduction: ['Off', 'Low', 'Medium', 'High']
  },
  'portrait-enhancer': {
    id: 'portrait-enhancer',
    name: 'Portrait Enhancer',
    category: 'Image',
    categoryKey: 'image',
    description: 'Professional portrait enhancement and retouching with AI. Automatically smooth skin, enhance eyes, fix lighting, and remove blemishes while maintaining natural-looking results.',
    icon: 'https://aitopia.ai/agent-images/portrait-enhancer-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/portrait-enhancer-1.webp'],
    rating: 4.6,
    reviews: '9.1K',
    price: '$0.25',
    features: ['Skin Smoothing', 'Eye Enhancement', 'Lighting Fix', 'Blemish Removal', 'Natural Results'],
    developer: 'MuleRun',
    // Enhancement specific options
    enhancementLevel: ['Subtle', 'Moderate', 'Strong'],
    features_toggle: ['Skin smoothing', 'Eye enhancement', 'Teeth whitening', 'Background blur']
  },
  'image-animator': {
    id: 'image-animator',
    name: 'Image Animator',
    category: 'Video',
    categoryKey: 'video',
    description: 'Transform static images into captivating animated videos with AI motion synthesis. Add parallax effects, depth estimation, and seamless loops to bring your photos to life.',
    icon: 'https://aitopia.ai/agent-images/image-animator-1.webp',
    screenshots: [],
    rating: 4.7,
    reviews: '4.2K',
    price: '$0.80',
    features: ['Motion Synthesis', 'Loop Creation', 'Depth Estimation', 'Parallax Effect', 'Camera Movement'],
    developer: 'Higgsfield AI',
    // Animation specific options
    motionTypes: ['Gentle sway', 'Parallax', 'Zoom', 'Pan', 'Custom'],
    loopOptions: ['Once', 'Loop', 'Boomerang'],
    durationOptions: ['3s', '5s', '10s']
  },
  'video-upscaler': {
    id: 'video-upscaler',
    name: 'Video Upscale',
    category: 'Video Enhancement',
    categoryKey: 'video',
    description: 'Enhance video quality and resolution with AI-powered upscaling technology. Improve video clarity, reduce noise, and enhance details while maintaining natural appearance.',
    icon: 'https://aitopia.ai/agent-images/video-upscaler-1.webp',
    screenshots: ["https://aitopia.ai/agent-images/video-upscaler-1.webp"],
    rating: 4.6,
    reviews: '3.8K',
    price: 'Credits-based',
    features: ['Quality enhancement', 'Resolution upscaling', 'Noise reduction', 'Detail preservation', 'Fast processing'],
    developer: 'Higgsfield AI',
    // Video upscaler specific options
    targetResolutions: ['720p', '1080p', '4K'],
    frameRates: ['Original', '30fps', '60fps'],
    stabilization: ['Off', 'Light', 'Standard', 'Strong']
  },
  'music-generator': {
    id: 'music-generator',
    name: 'Music Generator',
    category: 'Audio',
    categoryKey: 'audio',
    description: 'Create original music and sound effects with AI. Generate background tracks, ambient sounds, and full compositions in various genres using MusicGen technology.',
    icon: 'https://aitopia.ai/agent-images/music-generator-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/music-generator-1.webp'],
    rating: 4.5,
    reviews: '2.1K',
    price: '$0.50',
    features: ['MusicGen', 'Sound Effects', 'Ambient', 'Style Control', 'Multiple Genres'],
    developer: 'Higgsfield AI',
    // Music specific options
    genres: ['Pop', 'Electronic', 'Classical', 'Jazz', 'Ambient', 'Cinematic', 'Rock'],
    moods: ['Happy', 'Sad', 'Energetic', 'Calm', 'Dramatic', 'Mysterious'],
    durations: ['15s', '30s', '60s', '2min', '3min']
  },
  'voice-cloner': {
    id: 'voice-cloner',
    name: 'Voice Cloner',
    category: 'Audio',
    categoryKey: 'audio',
    description: 'Create realistic voice clones and text-to-speech with multiple voice presets. Support for 29+ languages with natural-sounding speech synthesis.',
    icon: 'https://aitopia.ai/agent-images/voice-cloner-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/voice-cloner-1.webp'],
    rating: 4.4,
    reviews: '1.8K',
    price: '$1.00',
    features: ['Voice Synthesis', 'Multiple Presets', 'Natural Speech', '29+ Languages', 'Custom Voices'],
    developer: 'Higgsfield AI',
    // Voice specific options
    voiceTypes: ['Male', 'Female', 'Child', 'Custom Clone'],
    languages: ['English', 'Spanish', 'French', 'German', 'Italian', 'Portuguese', 'Chinese', 'Japanese', 'Korean'],
    emotions: ['Neutral', 'Happy', 'Sad', 'Angry', 'Excited', 'Calm']
  },
  'ai-model-swap': {
    id: 'ai-model-swap',
    name: 'AI Model Swap',
    category: 'E-Commerce',
    categoryKey: 'ecommerce',
    description: 'Replace fashion models in product photos while perfectly preserving garments, poses, and backgrounds. Ideal for e-commerce sellers needing diverse model representation.',
    icon: 'https://aitopia.ai/agent-images/ai-model-swap-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/ai-model-swap-1.webp'],
    rating: 4.7,
    reviews: '5.6K',
    price: '$0.60',
    features: ['Model replacement', 'Garment preservation', 'Pose matching', 'Diverse models', 'Natural results'],
    developer: 'MuleRun',
    // Model swap specific options
    modelDiversity: ['All ethnicities', 'All ages', 'All genders'],
    bodyTypes: ['Slim', 'Athletic', 'Average', 'Plus size'],
    poseMatching: ['Auto', 'Manual adjust']
  },
  'chibi-sticker-maker': {
    id: 'chibi-sticker-maker',
    name: 'Chibi Sticker Maker',
    category: 'Creative',
    categoryKey: 'creative',
    description: 'Transform photos into adorable chibi-style stickers instantly. Create cute character stickers with multiple poses and expressions perfect for messaging apps.',
    icon: 'https://aitopia.ai/agent-images/chibi-sticker-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/chibi-sticker-1.webp'],
    rating: 4.9,
    reviews: '8.4K',
    price: '$0.50',
    features: ['Cute stickers', 'Multiple poses', 'Expression variants', 'Instant generation', 'Pack creation'],
    developer: 'MuleRun',
    popular: true,
    // Sticker specific options
    stickerStyles: ['Classic Chibi', 'Anime', 'Cartoon', 'Emoji style'],
    packSizes: ['6 stickers', '12 stickers', '24 stickers'],
    expressions: ['Happy', 'Sad', 'Angry', 'Surprised', 'Love', 'Cool', 'Sleepy', 'Confused']
  },
  'product-description-writer': {
    id: 'product-description-writer',
    name: 'Product Description Writer',
    category: 'Productivity',
    categoryKey: 'productivity',
    description: 'Generate compelling, SEO-optimized product descriptions instantly. Supports multiple e-commerce platforms with tone customization and benefit highlighting.',
    icon: 'https://aitopia.ai/agent-images/product-description-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/product-description-1.webp'],
    rating: 4.8,
    reviews: '18.2K',
    price: 'Free',
    features: ['Platform optimization', 'SEO integration', 'Multiple variations', 'Benefit highlighting', 'Tone control'],
    developer: 'MuleRun',
    // Writer specific options
    platforms: ['Amazon', 'Shopify', 'eBay', 'Etsy', 'WooCommerce', 'General'],
    tones: ['Professional', 'Casual', 'Luxury', 'Fun', 'Technical'],
    lengths: ['Short (50 words)', 'Medium (100 words)', 'Long (200 words)']
  },
  'meeting-transcriber': {
    id: 'meeting-transcriber',
    name: 'Meeting Transcriber',
    category: 'Productivity',
    categoryKey: 'productivity',
    description: 'Transcribe meeting recordings with summaries, action items, and export formats.',
    icon: 'https://aitopia.ai/agent-images/meeting-transcriber-1.webp',
    screenshots: [
      'https://aitopia.ai/agent-images/meeting-transcriber-1.webp'
    ],
    rating: 4.7,
    reviews: '9.1K',
    price: '$0.40',
    features: ['Summaries', 'Action items', 'Export options', 'Multiple formats'],
    developer: 'MuleRun'
  },
  'style-transfer': {
    id: 'style-transfer',
    name: 'Style Transfer',
    category: 'Creative',
    categoryKey: 'creative',
    description: 'Transform photos with 100+ artistic styles including Y2K, Fairycore, Gorpcore, Vintage, and more. Apply aesthetic presets for stunning visual transformations.',
    icon: 'https://aitopia.ai/agent-images/style-transfer-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/style-transfer-1.webp'],
    rating: 4.5,
    reviews: '7.3K',
    price: '$0.30',
    features: ['100+ Styles', 'Aesthetic Presets', 'Intensity Control', 'Custom Styles', 'Batch Processing'],
    developer: 'Higgsfield AI',
    // Style transfer specific options
    styleCategories: ['Classic Art', 'Modern', 'Aesthetic', 'Fantasy', 'Vintage'],
    popularStyles: ['Y2K', 'Fairycore', 'Gorpcore', 'Quiet Luxury', 'Medieval', 'Cyberpunk'],
    intensity: ['Subtle', 'Balanced', 'Strong', 'Maximum']
  },
  'recast-studio': {
    id: 'recast-studio',
    name: 'Recast',
    category: 'Video',
    categoryKey: 'video',
    description: 'Industry-leading character swap for any video in seconds. Full character recasting - swap entire character appearance while preserving motion.',
    icon: 'https://aitopia.ai/agent-images/recast-studio-1.webp',
    screenshots: [],
    rating: 4.9,
    reviews: '18.2K',
    price: '$3.00',
    features: ['Full Character Swap', 'Temporal Consistency', 'Video Processing', 'Expression Transfer'],
    developer: 'Higgsfield AI',
    popular: true
  },
  'comic-book': {
    id: 'comic-book',
    name: 'Comic Book Style',
    category: 'Creative',
    categoryKey: 'creative',
    description: 'Transform photos into comic book illustrations. Add halftone effects, bold lines, and vibrant colors for an authentic comic look.',
    icon: 'https://aitopia.ai/agent-images/comic-book-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/comic-book-1.webp'],
    rating: 4.6,
    reviews: '5.4K',
    price: '$0.25',
    features: ['Comic Style', 'Halftone Effects', 'Bold Lines', 'Color Pop'],
    developer: 'Higgsfield AI'
  },
  'renaissance': {
    id: 'renaissance',
    name: 'Renaissance Style',
    category: 'Creative',
    categoryKey: 'creative',
    description: 'Transform photos into Renaissance classical painting style. Get the look of old masters with oil painting effects and period-accurate aesthetics.',
    icon: 'https://aitopia.ai/agent-images/renaissance-style-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/renaissance-style-1.webp'],
    rating: 4.7,
    reviews: '6.8K',
    price: '$0.30',
    features: ['Classical Style', 'Oil Painting Effect', 'Period Accurate', 'Artistic Enhancement'],
    developer: 'Higgsfield AI'
  },
  'object-remover': {
    id: 'object-remover',
    name: 'Object Remover',
    category: 'Image',
    categoryKey: 'image',
    description: 'Remove unwanted objects from images using AI inpainting. Seamlessly erase people, items, or imperfections from photos.',
    icon: 'https://aitopia.ai/agent-images/object-remover-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/object-remover-1.webp'],
    rating: 4.7,
    reviews: '14.8K',
    price: '$0.20',
    features: ['Smart Inpainting', 'Mask Detection', 'Background Fill', 'Batch Processing'],
    developer: 'MuleRun',
    popular: true
  },
  'angles': {
    id: 'angles',
    name: 'Product Angles',
    category: 'E-Commerce',
    categoryKey: 'ecommerce',
    description: 'Generate multiple angle views of a product for e-commerce. Create 360-degree product showcases from a single image.',
    icon: 'https://aitopia.ai/agent-images/angles.webp',
    screenshots: ['https://aitopia.ai/agent-images/angles.webp'],
    rating: 4.7,
    reviews: '9.3K',
    price: '$0.60',
    features: ['Multi-angle Views', 'E-commerce Ready', 'Consistent Lighting', 'Product Focus'],
    developer: 'MuleRun'
  },
  'mockup-studio': {
    id: 'mockup-studio',
    name: 'Mockup Studio',
    category: 'E-Commerce',
    categoryKey: 'ecommerce',
    description: 'Generate product mockups for t-shirts, mugs, phone cases, and more. Perfect for print-on-demand and merchandise preview.',
    icon: 'https://aitopia.ai/agent-images/mockup-studio-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/mockup-studio-1.webp'],
    rating: 4.8,
    reviews: '11.2K',
    price: '$0.40',
    features: ['Multiple Product Types', 'Color Options', 'Angle Views', 'Studio Environments'],
    developer: 'MuleRun',
    popular: true
  },
  'smart-data-analyzer': {
    id: 'smart-data-analyzer',
    name: 'Smart Data Analyzer',
    category: 'Productivity',
    categoryKey: 'productivity',
    description: 'AI-powered data analysis with pattern detection, anomaly identification, and natural language insights. Upload CSV/JSON for instant analysis.',
    icon: 'https://aitopia.ai/agent-images/smart-data-analyzer-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/smart-data-analyzer-1.webp'],
    rating: 4.8,
    reviews: '12.3K',
    price: '$0.30',
    features: ['Statistical Analysis', 'Correlation Detection', 'Anomaly Detection', 'Data Quality Assessment'],
    developer: 'MuleRun'
  },
  'ai-assistant': {
    id: 'ai-assistant',
    name: 'AI Assistant',
    category: 'Productivity',
    categoryKey: 'productivity',
    description: 'Multi-agent orchestration and task management. Your personal AI assistant for complex workflows and task automation.',
    icon: 'https://aitopia.ai/agent-images/ai-assistant-1.webp',
    screenshots: ['https://aitopia.ai/agent-images/ai-assistant-1.webp'],
    rating: 4.9,
    reviews: '21.5K',
    price: '$1.00',
    features: ['Multi-Agent', 'Task Planning', 'Workflow Automation', 'Context Management'],
    developer: 'MuleRun',
    popular: true
  }
};
