OLD_FALLBACK_BOOKMARKING_URLS = [
    "https://99bookmarking.com",
    "https://a1bookmarks.com",
    "https://a2zbookmarking.com",
    "https://a2zbookmarks.com",
    "https://activebookmarks.com",
    "https://admyurl.com",
    "https://atavi.com",
    "https://bookmarkbid.com",
    "https://bookmarkbuzz.com",
    "https://bookmarkcircle.com",
    "https://bookmarkdiary.com",
    "https://bookmarkdrive.com",
    "https://bookmarkfollow.com",
    "https://bookmarkgroups.com",
    "https://bookmarkidea.com",
    "https://bookmarkinbox.com",
    "https://bookmarkinbox.info",
    "https://bookmarkinghost.com",
    "https://bookmarkinghost.info",
    "https://bookmarks2u.com",
    "https://bookmarkset.com",
    "https://bookmarkspirit.com",
    "https://bookmarktalk.com",
    "https://bookmarktalk.info",
    "https://bookmarktheme.com",
]


FALLBACK_BOOKMARKING_URLS = [
    "https://www.addressguru.in",
    "https://bookmark-dofollow.com/",
    "https://bookmark-template.com",
    "https://hindibookmark.com",
    "https://bookmarkstumble.com",
    "https://socialmarkz.com",
    "https://socialmphl.com",
    "https://bookmarkinglive.com",
    "https://johsocial.com/",
    "https://listfav.com/",
    "https://fatallisto.com/",
    "https://throbsocial.com/",
    "https://sitesrow.com/",
    "https://kingslists.com/",
    "https://hylistings.com",
    "https://bookmarkvids.com/",
    "https://travialist.com/",
]
