name: Automatic Release Builder

on:
  push:
    tags:
      - 'v*'


jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests
        
      - name: Build Executable File
        run: |
          pyinstaller --onefile --name "MainBrowserAgent" src/main.py

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/MainBrowserAgent.exe
          name: Release ${{ github.ref_name }}
          body: | 
            Automated Release for version ${{ github.ref_name }}.
          draft: false
          prerelease: false

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      
